### ISSUE TITLE
Windows Defender identifying a Trojan Horse in the download.

### ISSUE THREAD

**Issue by jawshey** [scottrice/Ice#329] opened 2016-01-04 20:52 UTC
Ice.zip is prevented from being downloaded by Windows Defender as it is picking up that there is Spursint.A infecting the file.

**Comment by scottrice** [comment] 2016-01-05 03:15
I've heard this in the past, and I think its due to how I built the original Ice executable. Its written in python (which doesnt compile to an exe natively) so I believe the way that pyinstaller packaged it it would extract the Ice code into a random directory and run it there. Unsurprisingly, thats super suspicious behavior and a lot of antivirus programs flag it.

I'm planning to use a different build system for the next version of Ice I put out which will hopefully not have this problem. I'm going to close this issue for now (since I think its a duplicate of another issue anyway), but I appreciate you reporting it.

**Closed by scottrice** 2016-01-05 03:15 UTC
