### ISSUE TITLE
None of my emulators detected. Pulling my hair out.

### ISSUE THREAD

**Issue by Albyint** [scottrice/Ice#357] opened 2016-01-26 20:02 UTC
Okay. Ice will not detect any of my emulators. I have tried and tried and I am about fed up. The line between each pasted file was added by me for organization.

Edit: I have followed multiple videos instructions, it has gotten to the point where i feel like it should be working..... but it just isnt.

______________________________________________________________________________

Log:

```
[01/26/16 13:56:05] =========================Starting Ice
[01/26/16 13:56:05] Emulator 'Dolphin' not found for Dolphin. Ignoring
[01/26/16 13:56:05] Emulator 'Project64' not found for Project64. Ignoring
[01/26/16 13:56:05] Emulator 'PCSX2' not found for PCSX2. Ignoring
[01/26/16 13:56:05] Emulator 'ePSXe' not found for ePSXe. Ignoring
[01/26/16 13:56:05] ---------------Running for user 31293560
[01/26/16 13:56:05] ---Downloading grid images
[01/26/16 13:56:05] =========================Finished
```
_______________________________________________________________________________
Config:

```
[Storage]
# The path to place your ROMs Directory. This can be in any drive or anywhere,
# as long as the full path is specified. Use ~ to represent your home folder
# (for example, C:\Users\Scott\)
#
# Set a directory where the ROMs are stored.
# If no directory is provided, "~/ROMs" is used.
# Example:
# ~\ROMs                     => C:\Users\<YOUR USERNAME>\ROMs
ROMs Directory=E:\Games\Source Files\Raw Files- Source Files\ROMS

[Grid Images]
# The website listed should provide the grid images used by Ice. This URL will
# most likely need to be provided by the website itself, as it is fairly specific.
#
# The default is ConsoleGrid (consolegrid.com/api/top_picture)
#
# If this field is left blank, Ice will not attempt to download images
Source=consolegrid.com/api/top_picture

[LinSnes9x]
download-location=http://powrtoch.org/public/linsnes9x.zip
relative-exe-path=linsnes9x/snes9x

[LinMednafen]
download-location=http://powrtoch.org/public/linmednafen.zip
relative-exe-path=linmednafen/mednafen

[LinePSXe]
download-location=http://powrtoch.org/public/linepsxe.zip
relative-exe-path=linepsxe/epsxe

[LinMupen64Plus]
download-location=http://powrtoch.org/public/linmupen64plus.zip
relative-exe-path=linmupen64plus/mupen64plus

[MacSnes9x]
download-location=http://consolegrid.com/ice_emulators/MacSnes9x.zip
relative-exe-path=MacSnes9x/Snes9x.app

[MacMednafen]
download-location=http://consolegrid.com/ice_emulators/MacMednafen.zip
relative-exe-path=MacMednafen/mednafen

[Winbsnes]
download-location=http://consolegrid.com/ice_emulators/Winbsnes.zip
relative-exe-path=Winbsnes\bsnes.exe

[WinProject64]
download-location=http://consolegrid.com/ice_emulators/WinProject64.zip
relative-exe-path=WinProject64\Project64-launcher.exe

[WinDolphin]
download-location=http://consolegrid.com/ice_emulators/WinDolphin.zip
relative-exe-path=Dolphin\Dolphin.exe

[WinePSXe]
download-location=http://consolegrid.com/ice_emulators/WinePSXe.zip
relative-exe-path=WinePSXe\ePSXe.exe

[WinPCSX2]
download-location=http://consolegrid.com/ice_emulators/WinPCSX2.zip
relative-exe-path=WinPCSX2\pcsx2-launcher.exe

[WinGens]
download-location=http://consolegrid.com/ice_emulators/WinGens.zip
relative-exe-path=WinGens\gens-launcher.exe

[WinVisualBoyAdvance]
download-location=http://consolegrid.com/ice_emulators/WinVisualBoyAdvance.zip
relative-exe-path=WinVisualBoyAdvance\VisualBoyAdvance.exe
```
_______________________________________________________________________________
Consoles:

```
[Project64]
nickname=Project64
emulator=Project64

[Dolphin]
nickname=Dolphin
emulator=Dolphin

[PCSX2]
nickname=PCSX2
emulator=PCSX2

[ePSXe]
nickname=ePSXe
emulator=ePSXe
```

Emulators:

```
# [PCSX2]
# location=C:\Program Files (x86)\PCSX2 1.4.0.exe
# command=%l %r

# [ePSXe]
# location=E:\Games\Source Files\Raw Files- Source Files\epsxe.exe
# command=%l -nogui -loadiso %r

# [Project64]
# location=E:\Games\Source Files\Raw Files- Source Files\p64\Project 64 2.1.exe
# command=%l %r

# [Dolphin]
# location=E:\Games\Source Files\Raw Files- Source Files\Gamecube\Dolphin-x64.exe
# command=%l --batch --exec=%r
```

**Comment by RobLoach** [comment] 2016-01-28 06:30
Use markdown code ```

**Comment by scottrice** [comment] 2016-01-29 04:06
Hey @Albyint, sorry this is being problematic for you.

It looks like you're running a //really// old version. Would you mind downloading the latest source? I'll also try to update the exe as well.

**Comment by LonelyTVy** [comment] 2016-01-30 19:52
@Albyint , Remove the # before each of the emulators and the two lines afterwards. For example change:

```
# [PCSX2]
# location=C:\Program Files (x86)\PCSX2 1.4.0.exe
# command=%l %r
```

to

```
[PCSX2]
location=C:\Program Files (x86)\PCSX2 1.4.0.exe
command=%l %r
```

Do this for all of them. In 99% of things dealing with config files and such the # sign signals a comment for a human and is ignored by the program. Also, ensure that the path to the emulator is correct.

**Comment by Albyint** [comment] 2016-01-31 01:20
Alright I shall give all these a try and get back to you!!

Thanks for the replies!! Really!! :-)

**Comment by Albyint** [comment] 2016-01-31 02:01
Holy shit, thanks so much, it now detects the emulators!!

**Comment by ProfessorKaos64** [comment] 2016-01-31 03:18
@Albyint , yep, typically in most plain text/configuration files, and predominantly see in Linux "bash scripts," the # character denotes a comment.

**Comment by RobLoach** [comment] 2016-01-31 04:17
Yay!

**Comment by scottrice** [comment] 2016-01-31 21:07
Glad you got it working! Looks like I need to work on usability :P.

Since the problem is resolved I'm going to close the issue. Let me know if theres anything else I can do to help.

**Closed by scottrice** 2016-01-31 21:07 UTC
